Repository kubernetes-sigs/metrics-server, pull requests merged in 2018-08, with the labels that each got.

#100 Extract storage installation for easy reuse
  pkg/apiserver/config.go
  pkg/apiserver/generic/storage.go
Labels: cncf-cla: yes, cncf-cla: yes, lgtm, size/L

#103 Fix travis to catch main command issues
  .travis.yml
  cmd/metrics-server/app/start.go
Labels: cncf-cla: yes, cncf-cla: yes, size/XS

#104 Add owners and security contacts files
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: cncf-cla: yes, cncf-cla: yes, lgtm, size/M

#108 Fix Prometheus bucket calculation
  pkg/metrics/util.go
  pkg/metrics/util_test.go
Labels: cncf-cla: yes, cncf-cla: yes, size/M

#102 Add generation before container build
  Makefile
Labels: cncf-cla: yes, size/XS

#116 Add deprecated completely insecure Kubelet option
  cmd/metrics-server/app/start.go
  pkg/sources/summary/client.go
  pkg/sources/summary/configs.go
Labels: cncf-cla: yes, size/M

#118 Modify package name in reststorage.go
  pkg/storage/nodemetrics/reststorage.go
  pkg/storage/podmetrics/reststorage.go
Labels: cncf-cla: yes, size/XS

#119 Use the earliest possible timestamp for metric points
  pkg/provider/sinkprov.go
  pkg/provider/sinkprov_test.go
  pkg/sources/summary/summary.go
  pkg/storage/nodemetrics/reststorage.go
  pkg/storage/podmetrics/reststorage.go
Labels: cncf-cla: yes, lgtm, size/M

#115 Change kubernetes dependencies to use release-1.11 branch as constraint
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.proto
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.deepcopy.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/lease_manager.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/apiserver/plugin/pkg/audit/buffered/buffered.go
  vendor/k8s.io/apiserver/plugin/pkg/audit/truncate/truncate.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
  vendor/k8s.io/client-go/transport/round_trippers.go
Labels: cncf-cla: yes, size/XXL

#113 Prep for v0.3.0 release
  README.md
Labels: cncf-cla: yes, size/M

#122 A few more changes for external provider support
  cmd/metrics-server/app/start.go
  pkg/provider/interfaces.go
  pkg/provider/sink/sinkprov.go
  pkg/provider/sink/sinkprov_test.go
  pkg/provider/sinkprov.go
  pkg/storage/nodemetrics/reststorage.go
  pkg/storage/podmetrics/reststorage.go
Labels: cncf-cla: yes, lgtm, size/XL

#127 Update 1.8+ deployment to v0.3.0
  deploy/1.8+/metrics-server-deployment.yaml
Labels: cncf-cla: yes, size/XS
