Repository kubernetes-sigs/metrics-server, pull requests merged in 2019-05, with the labels that each got.

#259 Some fix to Makefile "push".
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#236 Fix broken link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#260 Do not run as root by default in Docker
  deploy/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#261 Add golangci-lint to the CI pipeline of metrics-server
  .golangci.yml
  .travis.yml
  Makefile
  pkg/sources/interfaces.go
  pkg/sources/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#265 Fix typo in OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#266 Bump deployment yaml to v0.3.3
  deploy/1.8+/metrics-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#215 rm redundant return
  pkg/sources/manager.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, lifecycle/stale, size/XS
