Repository kubernetes-sigs/metrics-server, pull requests merged in 2019-11, with the labels that each got.

#341 Add serathius as owner
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#339 Update to stable "rbac.authorization.k8s.io/v1"
  deploy/1.8+/aggregated-metrics-reader.yaml
  deploy/1.8+/auth-delegator.yaml
  deploy/1.8+/auth-reader.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#273 Update link to Embargo Policy in SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#345 Change link name from "Embargo Poicy" to "Security Release Process"
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#337 Update the securityContext
  deploy/1.8+/metrics-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#354 Add flag --kubelet-certificate-authority to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#352 Use multi-stage image building
  Makefile
  deploy/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#367 Add nodeSelector to deploy only on Linux.
  deploy/1.8+/metrics-server-deployment.yaml
Labels: approved, cncf-cla: yes, size/XS

#366 Migrate repository path to sigs.k8s.io/metrics-server
  .golangci.yml
  Makefile
  cmd/metrics-server/app/start.go
  cmd/metrics-server/metrics-server.go
  deploy/docker/Dockerfile
  go.mod
  hack/calc-build-info.sh
  pkg/apiserver/config.go
  pkg/apiserver/generic/storage.go
  pkg/manager/manager.go
  pkg/metrics/util_test.go
  pkg/provider/sink/sinkprov.go
  pkg/provider/sink/sinkprov_test.go
  pkg/sink/interfaces.go
  pkg/sources/fake/fakes.go
  pkg/sources/manager.go
  pkg/sources/manager_test.go
  pkg/sources/summary/summary.go
  pkg/sources/summary/summary_test.go
  pkg/storage/nodemetrics/reststorage.go
  pkg/storage/nodemetrics/reststorage_test.go
  pkg/storage/podmetrics/reststorage.go
  pkg/storage/podmetrics/reststorage_test.go
Labels: approved, cncf-cla: yes, size/M

#359 report memory from RSSBytes instead of WorkingSetBytes
  pkg/sources/summary/summary.go
  pkg/sources/summary/summary_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
