Repository kubernetes-sigs/metrics-server, pull requests merged in 2019-04, with the labels that each got.

#245 add s-urbaniak, prune directxman12 from owners et al
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#240 Prune directxman12 from OWNERS, etc
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/XS

#243 Rebase metrics-server image to distroless
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#242 Bump to version v0.3.2
  deploy/1.8+/metrics-server-deployment.yaml
  pkg/sources/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
