Repository kubernetes-sigs/metrics-server, pull requests merged in 2019-10, with the labels that each got.

#324 Bump metrics-server version to v0.3.6
  deploy/1.8+/metrics-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#332 Upgrade golang versions to 1.12.12
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#201 run metrics server as non privileged user and in non rootfs
  deploy/1.8+/metrics-server-deployment.yaml
  deploy/1.8+/metrics-server-service.yaml
  deploy/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#279 Add --version flag
  cmd/metrics-server/app/start.go
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#336 Update all dependencies
  cmd/metrics-server/app/start.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L
