Repository kubernetes-sigs/metrics-server, pull requests merged in 2019-12, with the labels that each got.

#377 Update kube deps to 1.17.0.rc1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#368 Implement e2e tests using kind
  .travis.yml
  Makefile
  README.md
  deploy/1.8+/resource-reader.yaml
  go.mod
  go.sum
  test/e2e.sh
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#400 Adds multiple versions of Kubernetes to e2e tests
  .travis.yml
  Makefile
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
