Repository kubernetes-sigs/metrics-server, pull requests merged in 2020-09, with the labels that each got.

#585 Update service.yaml to have named port
  manifests/base/service.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#593 Remove unused hack directory
  hack/boilerplate.go.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#590 Fix kubelet metrics
  pkg/metrics-server/config.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#589 Fix kubelet config options
  Makefile
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/options/options_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#592 Adding livez and readyz endpoints
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/start.go
  manifests/base/deployment.yaml
  pkg/scraper/interface.go
  pkg/scraper/scraper.go
  pkg/scraper/types_easyjson.go
  pkg/server/config.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/storage/interface.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#595 Rename lint Makefile rule to verify
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#563 Remove KubeUp labels and use Kustomize commonLabels
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/base/pdb.yaml
  manifests/base/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#597 Update k8s versions in e2e tests and kind binary
  Makefile
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#591 Use k8s.io/kubelet/pkg/apis/stats to simplify module management
  Dockerfile
  Makefile
  go.mod
  go.sum
  pkg/scraper/types_test.go
  test/e2e.sh
  test/e2e_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/go.mod
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/go.sum
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#594 Implement storage and api metrics
  pkg/api/monitoring.go
  pkg/api/node.go
  pkg/api/node_test.go
  pkg/api/pod.go
  pkg/api/pod_test.go
  pkg/api/time.go
  pkg/storage/monitoring.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#599 Add verify and update makefile rules
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#587 pkg: dependency inject prometheus registry
  cmd/metrics-server/app/start.go
  pkg/api/monitoring.go
  pkg/api/node_test.go
  pkg/api/pod_test.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
  pkg/server/config.go
  pkg/server/metrics.go
  pkg/server/server.go
  pkg/storage/monitoring.go
  pkg/storage/storage_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
