Repository kubernetes-sigs/metrics-server, pull requests merged in 2020-12, with the labels that each got.

#659 Create TOC for KNOWN_ISSUES.md and FAQ.md
  FAQ.md
  KNOWN_ISSUES.md
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#657 Exclude healthz and livez probes from other endpoints
  manifests/base/deployment.yaml
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#658 Enable restclient metrics in metrics output
  pkg/server/config.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#662 Improve typos and readability
  FAQ.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#663 Bump Kubernetes to v1.20.0
  Makefile
  go.mod
  go.sum
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#664 Revert "Remove unused error"
  pkg/api/interfaces.go
  pkg/api/node.go
  pkg/api/node_test.go
  pkg/api/pod.go
  pkg/api/pod_test.go
  pkg/server/server_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
