Repository kubernetes-sigs/metrics-server, pull requests merged in 2020-03, with the labels that each got.

#453 Fix metrics and add e2e tests
  go.mod
  go.sum
  pkg/metrics-server/server.go
  pkg/scraper/scraper.go
  pkg/utils/monitoring.go
  pkg/utils/monitoring_test.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#454 Fix latency metrics
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#458 Fix vendor format
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#462 add faq about Problems with Calico NetworkPolicy deployment with Kubeadm
  FAQ.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#461 Use kubectl apply rather than create
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#464 beta.kubernetes.io/os -> kubernetes.io/os
  deploy/kubernetes/metrics-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#460 Add cloudbuild.yaml
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#467 add fat manifest on push
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#465 Add cloudbuild.yaml to 0.3 branch
  .gitignore
  .travis.yml
  Makefile
  cloudbuild.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/manager/manager.go
  pkg/sources/manager_test.go
  pkg/sources/summary/summary_test.go
Labels: cncf-cla: yes, size/XXL

#470 Cherry pick #467 into release-0.3
  Makefile
Labels: cncf-cla: yes, lgtm, size/S

#468 Cleanup Makefile
  Makefile
  hack/calc-build-info.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
