Repository kubernetes-sigs/metrics-server, pull requests merged in 2020-10, with the labels that each got.

#600 Invoke make from Dockerfile
  .gitignore
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#605 Update deprecated apiVersion of APIService
  manifests/base/apiservice.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#609 fix/github: typo /king bug -> /kind bug
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#611 docs: add section header for Helm Chart
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#612 github: add spoiler tags to bug report issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#620 pkg/*: move to klog/v2
  go.mod
  go.sum
  pkg/api/node.go
  pkg/api/pod.go
  pkg/scraper/decode.go
  pkg/scraper/scraper.go
  pkg/server/server.go
  pkg/storage/storage.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#624 added cmd flag validations
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/options/options_test.go
  cmd/metrics-server/app/start.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
