Repository kubernetes-sigs/metrics-server, pull requests merged in 2020-04, with the labels that each got.

#475 Fix cloud build
  Makefile
  cloudbuild.yaml
  hack/Makefile.buildinfo
Labels: approved, cncf-cla: yes, lgtm, size/M

#479 Cherry pick https://github.com/kubernetes-sigs/metrics-server/pull/475 to release-0.3
  Makefile
  cloudbuild.yaml
  hack/Makefile.buildinfo
  hack/calc-build-info.sh
Labels: cncf-cla: yes, size/L

#480 Cherry pick https://github.com/kubernetes-sigs/metrics-server/pull/352/files to release-0.3
  Makefile
  deploy/docker/Dockerfile
Labels: cncf-cla: yes, size/M

#481 Maintain the same ordering invariant that the Kube API server does
  pkg/api/node.go
  pkg/api/pod.go
  pkg/api/pod_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#488 Fix multi-arch image push
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#478 The metrics aggregated API should serve table results to `kubectl get`
  pkg/api/node.go
  pkg/api/node_test.go
  pkg/api/pod.go
  pkg/api/pod_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#490 go.mod: Fix invalid go version
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#484 Update RELEASE.md to use image build pipeline and manifests as part of release
  Makefile
  README.md
  RELEASE.md
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#486 Backport v0.3.6 manifests from origin/master
  deploy/1.8+/aggregated-metrics-reader.yaml
  deploy/1.8+/auth-delegator.yaml
  deploy/1.8+/auth-reader.yaml
  deploy/1.8+/metrics-server-deployment.yaml
  deploy/1.8+/metrics-server-service.yaml
  deploy/1.8+/resource-reader.yaml
Labels: cncf-cla: yes, lgtm, size/S

#485 Download kind binary
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#495 Configure rolling deployment without downtime
  deploy/kubernetes/metrics-server-deployment.yaml
  deploy/kubernetes/metrics-server-pdb.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#497 Setup handler for stop signal and propagate it to allow fast termination
  cmd/metrics-server/app/start.go
  cmd/metrics-server/metrics-server.go
  pkg/metrics-server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#500 Fix _output directory not created
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#498 Wait for node informer to sync allowing immediate scrape to succeed fixing readiness probe
  pkg/metrics-server/config.go
  pkg/metrics-server/server.go
  test/e2e.sh
  test/e2e_test.go
Labels: approved, cncf-cla: yes, size/M

#492 Update manifests to use multi arch image
  FAQ.md
  deploy/kubernetes/metrics-server-deployment.yaml
Labels: approved, cncf-cla: yes, priority/important-soon, size/XS

#489 Fix push-multi-arch rule
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#503 Add serathius to owners in release-0.3
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS

#507 Cherry pick of https://github.com/kubernetes-sigs/metrics-server/pull/484
  Makefile
  README.md
  RELEASE.md
Labels: cncf-cla: yes, size/M

#502 Cherry pick https://github.com/kubernetes-sigs/metrics-server/pull/492
  deploy/1.8+/metrics-server-deployment.yaml
Labels: cncf-cla: yes, size/XS

#505 Rewrite README.md to be more clearer for new users
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/M

#510 Refactor e2e.sh script
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#509 Split deployment directory and update installation instructions
  Dockerfile
  Makefile
  README.md
  manifests/aggregated-metrics-reader.yaml
  manifests/auth-delegator.yaml
  manifests/auth-reader.yaml
  manifests/metrics-apiservice.yaml
  manifests/metrics-server-deployment.yaml
  manifests/metrics-server-pdb.yaml
  manifests/metrics-server-service.yaml
  manifests/resource-reader.yaml
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/M

#524 Fix golangci version
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#511 Adopt Kustomize
  Makefile
  manifests/aggregated-metrics-reader.yaml
  manifests/auth-delegator.yaml
  manifests/auth-reader.yaml
  manifests/base/apiservice.yaml
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/base/pdb.yaml
  manifests/base/rbac.yaml
  manifests/base/service.yaml
  manifests/release/kustomization.yaml
  manifests/resource-reader.yaml
  manifests/test/kustomization.yaml
  manifests/test/patch.yaml
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#515 Change kubelet-preferred-address-types to match kubeadm
  manifests/base/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#513 Remove "no metrics know for pod" log
  pkg/api/node.go
  pkg/api/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#514 Change decoder error logs to info
  pkg/scraper/decode.go
  pkg/scraper/decode_test.go
  pkg/scraper/scraper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#518 Remove unused error
  pkg/api/interfaces.go
  pkg/api/node.go
  pkg/api/node_test.go
  pkg/api/pod.go
  pkg/api/pod_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#519 Upgrade golang to 1.14
  .travis.yml
  Dockerfile
  Makefile
  go.mod
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#508 Fix release-tag
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#521 Update e2e test cluster versions
  Makefile
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#517 Use Easyjson for parsing
  Makefile
  go.mod
  go.sum
  pkg/scraper/client.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/go.mod
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/go.sum
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types_easyjson.go
Labels: approved, cncf-cla: yes, size/XXL

#523 Disable cache when running e2e tests
  test/e2e.sh
Labels: approved, cncf-cla: yes, size/XS

#501 Remove Travis CI
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S
