Repository kubernetes-sigs/metrics-server, pull requests merged in 2020-02, with the labels that each got.

#414 refactor[yaml]: Updated the apiVersion of Deployment from extension/v1beta1 to apps/v1
  deploy/1.7/metrics-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#388 Fix typo in util.go
  pkg/metrics/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#423 Removed the manifests that is no longer needed
  README.md
  deploy/1.7/auth-delegator.yaml
  deploy/1.7/auth-reader.yaml
  deploy/1.7/metrics-apiservice.yaml
  deploy/1.7/metrics-server-deployment.yaml
  deploy/1.7/metrics-server-service.yaml
  deploy/kubernetes/aggregated-metrics-reader.yaml
  deploy/kubernetes/auth-delegator.yaml
  deploy/kubernetes/auth-reader.yaml
  deploy/kubernetes/metrics-apiservice.yaml
  deploy/kubernetes/metrics-server-deployment.yaml
  deploy/kubernetes/metrics-server-service.yaml
  deploy/kubernetes/resource-reader.yaml
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#426 Adopt K/K issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/support.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#427 Remove minikube instructions
  README.md
  deploy/minikube/metric-server-args.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#430 Document requirements for cluster/network
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#434 Add sig-instrumentation contact info
  .github/ISSUE_TEMPLATE/support.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#431 Add FAQ
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#438 Update golang to 1.13.8
  .travis.yml
  Makefile
  deploy/docker/Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#437 Update dependencies to 1.17.3 and minify
  deploy/docker/Dockerfile
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/go.mod
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#436 Update faq
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#439 Update golangci to 1.23.6
  Makefile
  pkg/sources/summary/summary_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#441 Fix version
  .travis.yml
  Makefile
  hack/Makefile.buildinfo
  test/version.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#444 Update README and move FAQ to seperate file
  .github/ISSUE_TEMPLATE/support.md
  CONTRIBUTING.md
  FAQ.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#445 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#446 Add release instructions
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#387 Refactor
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/start.go
  cmd/metrics-server/metrics-server.go
  pkg/api/generated/openapi/doc.go
  pkg/api/generated/openapi/zz_generated.openapi.go
  pkg/api/install.go
  pkg/api/interfaces.go
  pkg/api/node.go
  pkg/api/node_test.go
  pkg/api/pod.go
  pkg/api/pod_test.go
  pkg/apiserver/config.go
  pkg/metrics-server/config.go
  pkg/metrics-server/server.go
  pkg/scraper/client.go
  pkg/scraper/configs.go
  pkg/scraper/decode.go
  pkg/scraper/decode_test.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
  pkg/sink/interfaces.go
  pkg/sources/fake/fakes.go
  pkg/sources/manager.go
  pkg/sources/manager_test.go
  pkg/sources/summary/summary.go
  pkg/sources/summary/summary_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
  pkg/utils/address_resolver.go
  pkg/utils/monitoring.go
  pkg/utils/monitoring_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#452 Change imagePullPolicy to IfNotPresent
  deploy/kubernetes/metrics-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
