Repository kubernetes-sigs/metrics-server, pull requests merged in 2020-08, with the labels that each got.

#565 Add autoscaled manifest configuration
  manifests/autoscale/kustomization.yaml
  manifests/autoscale/patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#564 Rename port to https
  manifests/base/deployment.yaml
  manifests/base/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#570 Add CLI flags to pass cert/key for kubelet auth
  cmd/metrics-server/app/options/options.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#562 Fix nil pointer on config.Client.TLSClientConfig
  cmd/metrics-server/app/options/options.go
  pkg/scraper/configs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#580 fix typo in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
