Repository kubernetes-sigs/metrics-server, pull requests merged in 2020-06, with the labels that each got.

#538 Add the feature to get KubeletPort dynamically
  cmd/metrics-server/app/options/options.go
  manifests/base/deployment.yaml
  pkg/scraper/client.go
  pkg/scraper/configs.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#528 Skip parsing not used json fields
  Makefile
  go.mod
  go.sum
  pkg/scraper/client.go
  pkg/scraper/decode.go
  pkg/scraper/decode_test.go
  pkg/scraper/scraper_test.go
  pkg/scraper/types.go
  pkg/scraper/types_easyjson.go
  pkg/scraper/types_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/go.mod
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types_easyjson.go
Labels: approved, cncf-cla: yes, size/XXL

#527 Refactor kubeletClient
  cmd/metrics-server/app/options/options.go
  pkg/metrics-server/config.go
  pkg/metrics-server/server.go
  pkg/scraper/client.go
  pkg/scraper/configs.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
Labels: approved, cncf-cla: yes, size/L
