Repository kubernetes-sigs/metrics-server, pull requests merged in 2021-07, with the labels that each got.

#793 manifests: Improve "autoscale" kustomization
  manifests/autoscale/kustomization.yaml
  manifests/autoscale/patch.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#794 Rename master to main
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#795 Update Supported Kubernetes version for Metrics Server 0.6.x
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#797 manifests: Add RBAC for autoscale
  manifests/autoscale/kustomization.yaml
  manifests/autoscale/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#798 Add initContainer for e2e_test
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#802 Allow users to configure audit logs
  cmd/metrics-server/app/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#800 test-e2e: Pod runs two containers, one as a sidecar container
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
