Repository kubernetes-sigs/metrics-server, pull requests merged in 2021-11, with the labels that each got.

#882 Specify the arch passed as build arg in the distroless image (#848)
  Dockerfile
  skaffold.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#884 Remove elevated permissions from metrics-server
  Dockerfile
  Makefile
  manifests/base/deployment.yaml
  test/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#886 Add "allowPrivilegeEscalation" to the Kustomize template (#881)
  manifests/base/deployment.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#887 Cherrypick pull request #884 from shuaich/remove_elevated_permission to release-0.5
  Dockerfile
  Makefile
  manifests/base/deployment.yaml
  test/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#885 Add test for the architecture of the image which was built
  Makefile
  test/test-image.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#891 chore(chart): fix actions reop filter
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#897 [release-0.5] Specify the arch passed as build arg in the distroless image (#848)
  Dockerfile
  skaffold.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#898 [release-0.4] Specify the arch passed as build arg in the distroless image (#848)
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#899 Bump release to v0.5.2
  README.md
  manifests/release/kustomization.yaml
Labels: cncf-cla: yes, size/XS, approved

#900 Bump release to v0.4.5
  README.md
  manifests/release/kustomization.yaml
Labels: cncf-cla: yes, size/XS, approved

#892 chore(chart): fix chart testing args
  .github/workflows/lint-test-chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#903 feat(chart): update chart for v0.5.2
  charts/metrics-server/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#904 chore(chart): fix manifest upload in chart release ci
  .github/workflows/release-chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#893 reimplement parsing container start time
  pkg/scraper/client/resource/decode.go
  pkg/scraper/client/resource/decode_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#909 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#911 images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
