Repository kubernetes-sigs/metrics-server, pull requests merged in 2021-04, with the labels that each got.

#702 Bump k8s deps on 0.4 branch
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#704 Bump version to v0.4.3
  README.md
  manifests/release/kustomization.yaml
Labels: approved, cncf-cla: yes, size/XS

#705 Update version compatibility matrix
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#707 Increase image build timeout to 1 hour
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS

#708 Increase image build timeout to 1 hour
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS

#709 Set Metrics Server DefaultKubernetesUserAgent in user agent string
  Makefile
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/start.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#711 Use checksum to tag development images
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#716 Speed up builds by ignoring binaries
  .dockerignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#717 Remove BUILD_DATE arg from Dockerfile
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#713 Update dependencies, golang and kind images
  Dockerfile
  Makefile
  cloudbuild.yaml
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#712 Skaffold
  Makefile
  README.md
  skaffold.yaml
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#715 Rewrite Makefile arch rules to be clearer and fix autocomplete
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#681 Split ready and live probes
  manifests/base/deployment.yaml
  pkg/server/config.go
  pkg/server/server.go
  pkg/server/server_test.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#714 Rename testing version to cli tests
  Makefile
  test/test-cli.sh
  test/test-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#718 Don't build image twice
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#673 Rewrite MS to use cumulative metric
  pkg/scraper/decode.go
  pkg/scraper/decode_test.go
  pkg/scraper/types.go
  pkg/scraper/types_easyjson.go
  pkg/scraper/types_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/storage/interface.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#720 Fix generating openapi
  go.sum
  scripts/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#721 Avoid generating source files during building
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#719 Migrate to structured logging
  Makefile
  go.mod
  go.sum
  pkg/api/node.go
  pkg/api/pod.go
  pkg/scraper/decode.go
  pkg/scraper/interface.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/storage/storage.go
  scripts/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#724 Mark generated targets as phony to ensure they are always regenerated
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#726 Allow Metrics Server to listen on privileged ports
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#727 Allow Metrics Server to listen on privileged ports
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#730 Update manifests to use port 443
  Dockerfile
  Makefile
  cloudbuild.yaml
  manifests/base/deployment.yaml
  skaffold.yaml
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#733 [release-0.4] Make building with buildkit work on GCB
  Dockerfile
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#732 Bump version to v0.4.4
  README.md
  manifests/release/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
