Repository kubernetes-sigs/metrics-server, pull requests merged in 2021-05, with the labels that each got.

#740 Minor spelling correction on main README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#741 Fix e2e failed with error ertificates
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#742 Add benchmark command
  Makefile
  go.mod
  go.sum
  scripts/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#736 Make metric comparison test deterministic
  pkg/storage/storage_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#743 Prepare for v0.5.0 release
  README.md
  manifests/autoscale/patch.yaml
  manifests/base/deployment.yaml
  manifests/release/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#455 Add tests for metric accuracy
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#746 Metrics Server reports negative CPU usage for restarting pods
  pkg/scraper/decode.go
  pkg/scraper/types.go
  pkg/scraper/types_easyjson.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#751 Depend on CPU.Time and StartTime when decoding metrics
  pkg/scraper/decode.go
  pkg/scraper/decode_test.go
  pkg/scraper/scraper_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#752 Refactor: Move summary kubelet client implementation to client subdirectory
  Makefile
  cmd/metrics-server/app/options/kubelet_client.go
  cmd/metrics-server/app/options/kubelet_client_test.go
  pkg/scraper/client/configs.go
  pkg/scraper/client/interface.go
  pkg/scraper/client/summary/client.go
  pkg/scraper/client/summary/decode.go
  pkg/scraper/client/summary/decode_test.go
  pkg/scraper/client/summary/types.go
  pkg/scraper/client/summary/types_easyjson.go
  pkg/scraper/client/summary/types_test.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
  pkg/server/config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#754 Rename storage fields and comment
  pkg/scraper/client/summary/decode.go
  pkg/scraper/client/summary/decode_test.go
  pkg/scraper/client/summary/types_test.go
  pkg/scraper/scraper_test.go
  pkg/server/server_test.go
  pkg/storage/storage.go
  pkg/storage/storage_benchmark_test.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#756 Split storage into substructs for nodes and pods
  pkg/api/interfaces.go
  pkg/api/pod.go
  pkg/api/pod_test.go
  pkg/server/server_test.go
  pkg/storage/node.go
  pkg/storage/pod.go
  pkg/storage/storage.go
  pkg/storage/storage_benchmark_test.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#757 Fix mistake of storage test
  pkg/storage/storage_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#758 Refactor storage test
  pkg/storage/node_test.go
  pkg/storage/pod_test.go
  pkg/storage/storage_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#759 Skip metric point if usageCoreNanoSeconds or workingSetBytes is zero
  pkg/scraper/client/summary/decode.go
  pkg/scraper/client/summary/decode_test.go
  pkg/scraper/client/summary/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#753 Fixed negative CPU usage caused by kubelet's summary API
  pkg/storage/node.go
  pkg/storage/node_test.go
  pkg/storage/pod.go
  pkg/storage/pod_test.go
  pkg/storage/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#761 Increase verbosity of log old metric point and unity storage test com…
  pkg/storage/node.go
  pkg/storage/node_test.go
  pkg/storage/pod.go
  pkg/storage/pod_test.go
Labels: approved, cncf-cla: yes, size/M

#762 Store uint64 values
  pkg/scraper/client/summary/decode.go
  pkg/scraper/client/summary/decode_test.go
  pkg/scraper/client/summary/types_test.go
  pkg/scraper/scraper_test.go
  pkg/server/server_test.go
  pkg/storage/node.go
  pkg/storage/node_test.go
  pkg/storage/pod.go
  pkg/storage/pod_test.go
  pkg/storage/storage_benchmark_test.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
  pkg/storage/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#760 Update list of OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#766 Utilize container start time to speed up returning metrics for fresh …
  pkg/server/config.go
  pkg/storage/node_test.go
  pkg/storage/pod.go
  pkg/storage/pod_test.go
  pkg/storage/storage.go
  pkg/storage/storage_benchmark_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#768 Improve reliability of probes
  manifests/base/deployment.yaml
  pkg/server/config.go
  pkg/server/health.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/storage/pod_test.go
  pkg/storage/storage.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#771 Update dependencies
  Dockerfile
  Makefile
  go.mod
  go.sum
  test/test-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#772 Update documentation for v0.5.0 release
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#774 Cleanup logging of scrape errors
  pkg/scraper/client/summary/client.go
  pkg/scraper/scraper.go
  pkg/utils/address_resolver.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#775 should get empty metrics in one cycle for fresh new container's time …
  cmd/metrics-server/app/options/options.go
  pkg/storage/pod.go
  pkg/storage/pod_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#773 Optimize e2e test cases
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#776 fix typos
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#779 Move live reload documentation to CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M
