Repository kubernetes-sigs/metrics-server, pull requests merged in 2021-09, with the labels that each got.

#815 Add yangjunmyfm192085 as reviewer
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved

#670 Add Helm chart
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
  README.md
  charts/metrics-server/.helmignore
  charts/metrics-server/Chart.yaml
  charts/metrics-server/README.md
  charts/metrics-server/ci/ci-values.yaml
  charts/metrics-server/templates/NOTES.txt
  charts/metrics-server/templates/_helpers.tpl
  charts/metrics-server/templates/apiservice.yaml
  charts/metrics-server/templates/clusterrole-aggregated-reader.yaml
  charts/metrics-server/templates/clusterrole.yaml
  charts/metrics-server/templates/clusterrolebinding-auth-delegator.yaml
  charts/metrics-server/templates/clusterrolebinding.yaml
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/pdb.yaml
  charts/metrics-server/templates/psp.yaml
  charts/metrics-server/templates/rolebinding.yaml
  charts/metrics-server/templates/service.yaml
  charts/metrics-server/templates/serviceaccount.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XL, ok-to-test

#820 Fix helm chart ci
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
  charts/metrics-server/README.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#822 Add chart index for failed release
  index.yaml
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#823 Fix chart index missing download link
  index.yaml
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#808 Run e2e tests with high availability configuration
  Makefile
  manifests/test-ha/kustomization.yaml
  manifests/test-ha/patch.yaml
  skaffold.yaml
  test/e2e_test.go
  test/kind-ha-config.yaml
  test/test-e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#827 Fix test-e2e-ha CI job
  manifests/high-availability/pdb.yaml
Labels: cncf-cla: yes, size/XS

#807 wait to be able to compute the resource usage of all the containers of a pod before exposing its PodMetrics.
  pkg/storage/pod.go
  pkg/storage/pod_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#831 test/e2e_test: improve metrics comparison output
  test/e2e_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#839 cherry pick of #807 wait to be able to compute the resource usage of…
  pkg/api/generated/openapi/zz_generated.openapi.go
  pkg/storage/pod.go
  pkg/storage/pod_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#841 Don‘t use Kubelet start time for metrics-server--master branch
  pkg/storage/node.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#844 Bump dependencies and prepare to v0.5.1 release
  Dockerfile
  Makefile
  README.md
  go.mod
  go.sum
  manifests/release/kustomization.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#845 Add e2e tests for k8s version 1.22
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#846 manifests: Update addon-resizer to 1.8.14
  manifests/autoscale/patch.yaml
  manifests/autoscale/rbac.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
