Repository kubernetes-sigs/metrics-server, pull requests merged in 2021-02, with the labels that each got.

#672 [release-0.4] Prevent SubjectAccessReview requests to hang forever
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-ok-to-test, priority/important-soon, size/M

#675 Bump version to v0.4.2
  manifests/release/kustomization.yaml
Labels: approved, cncf-cla: yes, size/XS

#680 Fix metric-resolution flag in FAQ doc.
  FAQ.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#676 Increase image push timeout to 30 minutes
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#678 Update golang and dependencies
  Dockerfile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#679 Use json6902 patch to inject --kubelet-insecure-tls flag
  manifests/test/kustomization.yaml
  manifests/test/patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#684 Improve logging in api
  pkg/api/node.go
  pkg/api/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#683 Group flags
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/start.go
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#686 Fix gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#651 Watch only metadata for pods
  cmd/metrics-server/app/start.go
  pkg/api/install.go
  pkg/api/pod.go
  pkg/api/pod_test.go
  pkg/server/config.go
  pkg/server/health.go
  pkg/server/informer.go
  pkg/server/server.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#685 Split kubelet client options
  cmd/metrics-server/app/options/kubelet_client.go
  cmd/metrics-server/app/options/kubelet_client_test.go
  cmd/metrics-server/app/options/options.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L
