Repository kubernetes-sigs/metrics-server, pull requests merged in 2021-10, with the labels that each got.

#847 Updates E2E test images registry
  test/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#852 Update golang to 1.17.1
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#851 Minimize rbac permissions
  manifests/base/rbac.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#854 Update module scripts
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#853 Update golang modules to match K8s 1.22.2
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
  pkg/storage/main_test.go
  pkg/storage/node_test.go
  pkg/storage/pod_test.go
  pkg/storage/storage_benchmark_test.go
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#855 Update e2e tooling
  Makefile
  test/test-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#856 Update org-wide default files based on https://github.com/kubernetes-…
  SECURITY.md
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S, lgtm, approved

#860 Set http client timeout
  pkg/scraper/client/resource/client.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#858 Enable more golangci-lint linters and cleanup code
  .golangci.yml
  cmd/metrics-server/app/options/kubelet_client.go
  cmd/metrics-server/app/options/kubelet_client_test.go
  cmd/metrics-server/app/options/options.go
  pkg/api/install.go
  pkg/api/node.go
  pkg/api/pod.go
  pkg/scraper/client/resource/client.go
  pkg/scraper/client/resource/decode.go
  pkg/server/server.go
  pkg/storage/pod.go
  pkg/storage/pod_test.go
  pkg/storage/storage_benchmark_test.go
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#861 Reduce allocations made by metric parsing
  go.mod
  go.sum
  pkg/scraper/client/interface.go
  pkg/scraper/client/resource/client.go
  pkg/scraper/client/resource/client_test.go
  pkg/scraper/client/resource/decode.go
  pkg/scraper/client/resource/decode_test.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
  pkg/server/config.go
Labels: cncf-cla: yes, lgtm, approved, size/XL
