Repository kubernetes-sigs/metrics-server, pull requests merged in 2021-08, with the labels that each got.

#806 Automate release manifests publication
  .github/workflows/release.yaml
  Makefile
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#805 Add high availability configuration
  .github/workflows/release.yaml
  Makefile
  README.md
  manifests/high-availability/kustomization.yaml
  manifests/high-availability/patch.yaml
  manifests/high-availability/pdb.yaml
  skaffold.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#817 Update golang used in metrics-server to 1.17
  Dockerfile
  Makefile
  pkg/api/generated/openapi/zz_generated.openapi.go
Labels: cncf-cla: yes, size/XS, lgtm, approved
