Repository kubernetes-sigs/metrics-server, pull requests merged in 2021-06, with the labels that each got.

#784 fix typo in error message
  pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#786 Fix incorrect description
  pkg/storage/node.go
  pkg/storage/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#788 Change storage batch to use map instead of list
  pkg/scraper/client/summary/decode.go
  pkg/scraper/client/summary/decode_test.go
  pkg/scraper/client/summary/types_test.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
  pkg/server/server_test.go
  pkg/storage/node.go
  pkg/storage/node_test.go
  pkg/storage/pod.go
  pkg/storage/pod_test.go
  pkg/storage/storage.go
  pkg/storage/storage_benchmark_test.go
  pkg/storage/types.go
  scripts/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#789 Update FAQ information about CPU and memory units
  FAQ.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#790 Provide alternative to using Metrics Server as source of metrics.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#777 Implement using /metrics/resource Kubelet endpoint
  Makefile
  go.mod
  go.sum
  manifests/base/rbac.yaml
  pkg/scraper/client/interface.go
  pkg/scraper/client/resource/client.go
  pkg/scraper/client/resource/decode.go
  pkg/scraper/client/resource/decode_test.go
  pkg/scraper/client/summary/decode.go
  pkg/scraper/client/summary/decode_test.go
  pkg/scraper/client/summary/types.go
  pkg/scraper/client/summary/types_easyjson.go
  pkg/scraper/client/summary/types_test.go
  pkg/server/config.go
  pkg/storage/node_test.go
  pkg/storage/pod_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
