Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-02, with the labels that each got.

#952 5->6
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#950 feat(chart): Update chart for v0.6.0
  charts/metrics-server/Chart.yaml
  charts/metrics-server/README.md
  charts/metrics-server/templates/clusterrole.yaml
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/servicemonitor.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#951 fix(manifests): Turn autoscale into a component
  manifests/autoscale/kustomization.yaml
  manifests/components/autoscale/kustomization.yaml
  manifests/components/autoscale/patch.yaml
  manifests/components/autoscale/rbac.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#954 Add chart CI for v0.6.0
  .github/workflows/release-chart.yaml
  charts/metrics-server/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#953 refactor(manifests): Follow base-components-overlays structure
  Makefile
  manifests/components/autoscale/rbac.yaml
  manifests/components/high-availability/kustomization.yaml
  manifests/components/high-availability/patch.yaml
  manifests/components/high-availability/pdb.yaml
  manifests/components/release/kustomization.yaml
  manifests/components/test/kustomization.yaml
  manifests/high-availability/kustomization.yaml
  manifests/overlays/release-ha/kustomization.yaml
  manifests/overlays/release/kustomization.yaml
  manifests/overlays/test-ha/kustomization.yaml
  manifests/overlays/test/kustomization.yaml
  manifests/release/kustomization.yaml
  manifests/test-ha/kustomization.yaml
  manifests/test-ha/patch.yaml
  manifests/test/kustomization.yaml
  manifests/test/patch.yaml
  skaffold.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#956 Bump version to v0.6.1
  README.md
  manifests/release/kustomization.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#959 Release chart for v0.6.1
  .github/workflows/release-chart.yaml
  charts/metrics-server/Chart.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#870 Fix charts and helm e2e test
  skaffold.yaml
  test/test-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#960 chart - making liveness and readiness probe configurable
  charts/metrics-server/templates/deployment.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, tide/merge-method-squash, ok-to-test

#967 Release chart v3.8.2
  charts/metrics-server/Chart.yaml
  charts/metrics-server/templates/deployment.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#968 Support logs in JSON format
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/start.go
  docs/command-line-flags.txt
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved
