Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-10, with the labels that each got.

#1100 Helm Chart: Adding additional labels to chart objects
  charts/metrics-server/README.md
  charts/metrics-server/templates/_helpers.tpl
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1102 Allow configuring TLS on the APIService
  charts/metrics-server/README.md
  charts/metrics-server/templates/apiservice.yaml
  charts/metrics-server/templates/serviceaccount.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, helm-chart

#1103 Allow configuring Deployment annotations in the Helm chart
  charts/metrics-server/README.md
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1110 Update description of cgroupv2 support in known issues
  KNOWN_ISSUES.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1112 feat: enable service monitor relabeling
  charts/metrics-server/templates/servicemonitor.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
