Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-08, with the labels that each got.

#1073 try to fix golangci-lint error
  Makefile
  cmd/metrics-server/app/options/kubelet_client.go
  cmd/metrics-server/app/options/kubelet_client_test.go
  cmd/metrics-server/app/options/options.go
  pkg/api/time.go
  pkg/server/config.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1074 bump golangci-lint version from 1.46.2 to 1.148.0
  Makefile
  cmd/metrics-server/app/options/kubelet_client.go
  cmd/metrics-server/app/options/kubelet_client_test.go
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/options/options_test.go
  pkg/api/time.go
  pkg/server/config.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1076 upgrade go version to 1.19
  Dockerfile
  Makefile
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1072 [release-0.5] Update go version to 1.16.15
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test
