Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-01, with the labels that each got.

#929 Bump dependencies and version to v0.6.0
  Dockerfile
  Makefile
  go.mod
  go.sum
  manifests/release/kustomization.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#935 Validate OWNERS files
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup, approved, ok-to-test

#931 Test Kubernetes v1.23
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#936 Update known causes for missing node metrics
  KNOWN_ISSUES.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#934 Restore support for log specific flags in Kubernetes Components
  cmd/metrics-server/app/start.go
  cmd/metrics-server/metrics-server.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#940 Test logging flags
  manifests/test/patch.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#942 Restore support for log specific flags in release-0.6 branch
  cmd/metrics-server/app/start.go
  cmd/metrics-server/metrics-server.go
  docs/command-line-flags.txt
  manifests/test/patch.yaml
  test/test-image.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#944 Update chart for 'v0.6.0' and update GH actions to release chart from release branches
  .github/workflows/release-chart.yaml
  charts/metrics-server/Chart.yaml
  charts/metrics-server/README.md
  charts/metrics-server/templates/clusterrole.yaml
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/servicemonitor.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#939 Document command line flags and test it
  docs/command-line-flags.txt
  test/test-image.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#945 adding another possible cause for network problem
  KNOWN_ISSUES.md
Labels: cncf-cla: yes, size/XS, lgtm, needs-ok-to-test, approved
