Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-11, with the labels that each got.

#1113 fix: add prometheus sm relabeling info to Readme
  charts/metrics-server/README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1107 Autoformat Helm chart values table in README.md
  charts/metrics-server/README.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#1124 update prometheus version to fix CVEs
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1126 Upload metrics-server logs in CI
  test/test-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#1128 cloudbuild: remove buildx-specific commands
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup, approved

#1132 Fix CVEs impacting release-0.6 branch
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved

#1133 Bump to release v0.6.2
  README.md
  manifests/release/kustomization.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1136 update go version and update the kubernetes image for e2e tests
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved

#1137 Add HA manifests compatible with 1.25+ to release-0.6
  Makefile
  manifests/high-availability-1.25+/kustomization.yaml
  manifests/high-availability-1.25+/patch-pdb-version.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1138 Recommend using policy/v1 starting from 1.21 on release-0.6
  Makefile
  manifests/high-availability-1.21+/kustomization.yaml
  manifests/high-availability-1.21+/patch-pdb-version.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1140 Update HA instructions to include 1.21+ deployment
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved
