Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-06, with the labels that each got.

#1035 verify test:fix golangci-lint
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#970 Set Helm chart resource namespaces explicitly
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/pdb.yaml
  charts/metrics-server/templates/rolebinding.yaml
  charts/metrics-server/templates/service.yaml
  charts/metrics-server/templates/serviceaccount.yaml
  charts/metrics-server/templates/servicemonitor.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1033 e2e test: update kind version to 1.24
  Makefile
  test/test-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#1038 fix(doc): imagePullSecrets example
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1041 Fix document: replace a broken link on README.md
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1045 Update test and readme for release 0.5
  Makefile
  README.md
  go.mod
  go.sum
  test/test-e2e.sh
Labels: cncf-cla: yes, size/M, lgtm, approved

#1043 update kind and golangci-lint version
  Makefile
  test/test-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#1042 Fix document: replace a broken link on README.md(cherrypick:https:https://github.com/kubernetes-sigs/metrics-server/pull/1041)
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1050 update logcheck
  Makefile
  go.mod
  go.sum
  scripts/tools.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1051 Optimize KNOWN_ISSUES
  KNOWN_ISSUES.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#1053 update logcheck for release0.5
  Makefile
  go.mod
  go.sum
  scripts/tools.go
Labels: cncf-cla: yes, size/S, lgtm, approved
