Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-09, with the labels that each got.

#1082 Update registry location to registry.k8s.io
  FAQ.md
  README.md
  charts/metrics-server/README.md
  charts/metrics-server/values.yaml
  manifests/components/autoscale/patch.yaml
  manifests/components/release/kustomization.yaml
  test/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1086 Link to PSS (since PSP is deprecated).
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1088 Added e2e test support for kubernetes v1.25 version
  Makefile
  test/test-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#1090 Upgrade the api dependency of metrics-server to v0.25.0
  cmd/metrics-server/app/options/options.go
  docs/command-line-flags.txt
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
  pkg/api/node.go
  pkg/api/pod.go
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1057 add Metrics-server scrape node timeout to KNOWN_ISSUES
  KNOWN_ISSUES.md
Labels: cncf-cla: yes, size/M, lgtm, approved
