Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-04, with the labels that each got.

#1001 add HPA is unable to compute the replica count for KNOWN_ISSUES
  KNOWN_ISSUES.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#1003 helm_chart: add link to scaling documentation
  charts/metrics-server/README.md
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1005 Remove redundant informer startup
  pkg/server/config.go
  pkg/server/server.go
  test/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1007 Optimize the timeout setting and timeout logging of metrics-server accessing the /metrics/resource endpoint
  cmd/metrics-server/app/options/kubelet_client.go
  cmd/metrics-server/app/options/kubelet_client_test.go
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/options/options_test.go
  docs/command-line-flags.txt
  pkg/scraper/scraper.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1009 fix: Handle error while parsing node metrics
  pkg/scraper/client/resource/client.go
  pkg/scraper/client/resource/decode.go
  pkg/scraper/client/resource/decode_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#1015 Update go version to 1.18.1
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1011 Handle error while parsing metrics(cherrypick: https://github.com/kubernetes-sigs/metrics-server/pull/1009)
  go.mod
  go.sum
  pkg/scraper/client/resource/client.go
  pkg/scraper/client/resource/decode.go
  pkg/scraper/client/resource/decode_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved
