Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-12, with the labels that each got.

#1144 feat(chart): Update chart for v0.6.2 image
  charts/metrics-server/Chart.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, triage/accepted

#1146 Release Helm chart v3.8.3
  charts/metrics-server/Chart.yaml
  charts/metrics-server/README.md
  charts/metrics-server/templates/_helpers.tpl
  charts/metrics-server/templates/apiservice.yaml
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/pdb.yaml
  charts/metrics-server/templates/rolebinding.yaml
  charts/metrics-server/templates/service.yaml
  charts/metrics-server/templates/serviceaccount.yaml
  charts/metrics-server/templates/servicemonitor.yaml
  charts/metrics-server/values.yaml
  skaffold.yaml
  test/test-e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#1149 Publish high-availability-1.21+ manifest
  .github/workflows/release.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1150 Remove manual assets publication step from RELEASE.md
  RELEASE.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1147 chore: Updated Helm automation
  .github/dependabot.yaml
  .github/workflows/gh-workflow-approve.yaml
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
  .github/workflows/release.yaml
  charts/metrics-server/README.md
  skaffold.yaml
  test/test-e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#1162 e2e test adds support for kubernetes version 1.26
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1120 feat(helm): add autoscaling to helm chart
  charts/metrics-server/README.md
  charts/metrics-server/templates/_helpers.tpl
  charts/metrics-server/templates/clusterrole-nanny.yaml
  charts/metrics-server/templates/clusterrolebinding-nanny.yaml
  charts/metrics-server/templates/configmaps-nanny.yaml
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/role-nanny.yaml
  charts/metrics-server/templates/rolebinding-nanny.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test
