Repository kubernetes-sigs/metrics-server, pull requests merged in 2022-03, with the labels that each got.

#977 Add support for topologySpreadConstraints to Helm Chart
  charts/metrics-server/README.md
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#969 document what ports are required for MS to work in the README
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#978 fix benchmark bug and some small spell mistake
  pkg/server/server_test.go
  pkg/storage/node_test.go
  pkg/storage/pod_test.go
  pkg/storage/storage_benchmark_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#979 Small cleanups for network requirements
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#980 Update description of KNOWN_ISSUES.md
  KNOWN_ISSUES.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#981 try to fix the e2e failure
  test/e2e_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#984 Add KNOWN ISSUES for EKS users
  KNOWN_ISSUES.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#995 dependencies: update x/tools for Go 1.18
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, lgtm, approved
