Repository kubernetes-sigs/metrics-server, pull requests merged in 2023-09, with the labels that each got.

#1328 Fix pull-metrics-server-test-version by running container only if local architecture matches
  test/test-image.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#1321 go.mod: Move tools into own go.mod
  Makefile
  go.mod
  go.sum
  scripts/go.mod
  scripts/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#1320 Replace which with command -v
  Makefile
  test/test-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, triage/accepted

#1322 docs: Cleanup
  .github/ISSUE_TEMPLATE/bug-report.md
  CONTRIBUTING.md
  FAQ.md
  KNOWN_ISSUES.md
  README.md
  SECURITY.md
  charts/metrics-server/README.md
  pkg/utils/monitoring_test.go
Labels: cncf-cla: yes, lgtm, size/L, needs-ok-to-test, approved, triage/accepted

#1332 bump k8s dependencies to v1.28
  cmd/metrics-server/app/options/options.go
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#1333 update kind dependencies
  Makefile
  test/test-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage
