Repository kubernetes-sigs/metrics-server, pull requests merged in 2023-03, with the labels that each got.

#1194 Fix CRITICAL/ HIGH security vulns in v0.6.2 reported by Trivy
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
Labels: cncf-cla: yes, lgtm, approved, size/XL, ok-to-test, triage/accepted

#1192 Changed the registry location to registry.k8s.io
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
  charts/metrics-server/Chart.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#1208 update golang to 1.19.6(fix CVE-2022-41723,CVE-2022-41725)
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#1210 [release-0.6] *: update registry location to registry.k8s.io
  FAQ.md
  README.md
  charts/metrics-server/README.md
  manifests/autoscale/patch.yaml
  manifests/release/kustomization.yaml
  manifests/test-ha/kustomization.yaml
  test/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1220 helm: fixes service annotation
  charts/metrics-server/templates/service.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, triage/accepted

#1227 chore(chart): Defined chart release v3.9.0
  charts/metrics-server/Chart.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, triage/accepted
