Repository kubernetes-sigs/metrics-server, pull requests merged in 2023-11, with the labels that each got.

#1348 Create Dependabot Configuation to support Docker and go module updates
  .github/dependabot.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, triage/accepted

#1370 update e2e tools and bump golang to 1.20.11 in dockerfile
  Dockerfile
  test/test-e2e.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1368 Bump otel libraries.
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XL, ok-to-test, needs-triage

#1380 bump prometheus libaries
  go.mod
  go.sum
  pkg/scraper/client/resource/decode.go
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1381 Bump golang to 1.21.4 and gcr.io/k8s-staging-test-infra/gcb-docker-gcloud
  Dockerfile
  Makefile
  cloudbuild.yaml
  go.mod
  go.sum
  scripts/go.mod
  scripts/go.sum
  test/e2e_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage
