Repository kubernetes-sigs/metrics-server, pull requests merged in 2023-07, with the labels that each got.

#1284 e2e test update support for kubernetes version
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1293 [release-0.6] Build image with go 1.19.11
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1297 *: cut release v0.6.4
  README.md
  manifests/release/kustomization.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1304 Update autoscaling configuration to follow README recommendation
  manifests/components/autoscale/patch.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1305 Updated addon-resizer patch version
  manifests/components/autoscale/patch.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1302 feat(chart): Added changes for v3.11.0
  charts/metrics-server/Chart.yaml
  charts/metrics-server/README.md
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#1300 kernel bug lead to incorrect cpu usage
  pkg/storage/types.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, triage/accepted
