Repository kubernetes-sigs/metrics-server, pull requests merged in 2023-12, with the labels that each got.

#1369 Add containerSecurityContext for addonResizer
  charts/metrics-server/README.md
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/values.yaml
  manifests/components/autoscale/patch.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, triage/accepted

#1331 add tests for sidecar containers
  Makefile
  test/e2e_test.go
  test/kind-config-with-sidecar-containers.yaml
  test/test-e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#1247 README.md
  charts/metrics-server/README.md
Labels: cncf-cla: yes, size/XS, lgtm, lifecycle/stale, approved, ok-to-test, triage/accepted

#1389 Configure e2e to be arm & darwin compatible
  test/test-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1391 Update OWNERS
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1336 fix markdown cve
  scripts/go.mod
  scripts/go.sum
Labels: cncf-cla: yes, size/XS, lgtm, approved, triage/accepted

#1393 Update RELEASE.md
  RELEASE.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, triage/accepted
