Repository kubernetes-sigs/metrics-server, pull requests merged in 2023-06, with the labels that each got.

#1262 Fix: Incorporate `-w` into `LDFLAGS`
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, needs-triage

#1273 Update golangci-lint to v1.53.2
  .golangci.yml
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1272 Bump Kubernetes deps to v0.27.2 and go to v1.20.5
  Dockerfile
  docs/command-line-flags.txt
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
  pkg/api/node.go
  pkg/api/pod.go
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#1276 chore: Fixed gh workflow approve
  .github/workflows/gh-workflow-approve.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, triage/accepted

#1280 fix some comments
  KNOWN_ISSUES.md
  cmd/metrics-server/app/options/kubelet_client.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, needs-triage
