Repository kubernetes-sigs/metrics-server, pull requests merged in 2023-04, with the labels that each got.

#1232 Set namespace for auth-reader rb to kube-system
  charts/metrics-server/templates/rolebinding.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, triage/accepted

#1234 Helm: Fix addon resizer role and configMap
  charts/metrics-server/templates/_helpers.tpl
  charts/metrics-server/templates/configmaps-nanny.yaml
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/role-nanny.yaml
  charts/metrics-server/templates/rolebinding-nanny.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, needs-triage

#1240 Permit running under PodSecurity restricted
  charts/metrics-server/values.yaml
  manifests/base/deployment.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, triage/accepted

#1244 Release Helm Chart v3.10.0
  charts/metrics-server/Chart.yaml
  charts/metrics-server/templates/_helpers.tpl
  charts/metrics-server/templates/configmaps-nanny.yaml
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/role-nanny.yaml
  charts/metrics-server/templates/rolebinding-nanny.yaml
  charts/metrics-server/templates/rolebinding.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, triage/accepted

#1245 Update Helm chart version on master
  charts/metrics-server/Chart.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1248 update kubernetes version to 1.27 for e2e
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage
