Repository kubernetes-sigs/metrics-server, pull requests merged in 2023-08, with the labels that each got.

#1309 [release-0.6] cherrypick #1300 kernel bug lead to incorrect cpu usage
  pkg/storage/types.go
  pkg/storage/types_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#1307 add test for resourceUsage
  pkg/storage/types_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#1310 update k8s version for e2e tests
  Makefile
  manifests/test-ha/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1253 Support modify metric collection path
  pkg/scraper/client/resource/client.go
Labels: cncf-cla: yes, size/S, lgtm, approved, triage/accepted

#1298 Add release binaries
  .github/workflows/release.yaml
  Makefile
Labels: cncf-cla: yes, size/M, lgtm, approved, triage/accepted

#1317 Include Prometheus parser improvements
  go.mod
  go.sum
  pkg/scraper/client/resource/decode.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, needs-triage
