Repository kubernetes-sigs/metrics-server, pull requests merged in 2023-01, with the labels that each got.

#1097 docs: point helm chart repo to metrics server github
  index.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1164 update golang to 1.19.4(fix CVE-2022-41717)
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1143 golangci-lint: fix goimports & add staticcheck
  .golangci.yml
  Makefile
  cmd/metrics-server/app/options/kubelet_client.go
  cmd/metrics-server/app/options/kubelet_client_test.go
  cmd/metrics-server/app/options/options.go
  cmd/metrics-server/app/start.go
  pkg/api/node.go
  pkg/api/pod.go
  pkg/scraper/client/interface.go
  pkg/scraper/client/resource/client.go
  pkg/scraper/client/resource/decode.go
  pkg/scraper/client/resource/decode_test.go
  pkg/scraper/scraper.go
  pkg/scraper/scraper_test.go
  pkg/server/config.go
  pkg/server/server_test.go
  pkg/storage/types.go
  test/e2e_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1156 GO-2022-1144: Bump golang.org/x/net
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1171 fix typos
  cmd/metrics-server/app/options/options.go
  pkg/storage/types.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, needs-triage

#1176 Fixed incorrect branch for gh workflow approve
  .github/workflows/gh-workflow-approve.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1172 fix metrics-server tests error infomation
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1178 Fixed GH workflow approval typo
  .github/workflows/gh-workflow-approve.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, triage/accepted

#1177 Fix README.md typo
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, needs-triage

#1180 Stop tagging helm chart releases as "latest"
  .github/workflows/release-chart.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1119 try to fix e2e test failure
  test/e2e_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved
