Repository kubernetes-sigs/metrics-server, pull requests merged in 2024-06, with the labels that each got.

#1502 fix comment typo in pkg/storage/pod.go
  pkg/storage/pod.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, needs-triage

#1504 chore(chart): Update `addon-resizer` version
  charts/metrics-server/CHANGELOG.md
  charts/metrics-server/README.md
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, triage/accepted

#1512 update dependencies manually
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage
