Repository kubernetes-sigs/metrics-server, pull requests merged in 2024-10, with the labels that each got.

#1288 feat(helm chart): Add metrics-server hardening options
  .github/workflows/lint-test-chart.yaml
  charts/metrics-server/CHANGELOG.md
  charts/metrics-server/README.md
  charts/metrics-server/ci/tls-certManager-values.yaml
  charts/metrics-server/ci/tls-existingSecret-values.yaml
  charts/metrics-server/ci/tls-helm-values.yaml
  charts/metrics-server/templates/apiservice.yaml
  charts/metrics-server/templates/certificate.yaml
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, lifecycle/rotten, approved, ok-to-test, triage/accepted

#1579 release-0.7: update golangci-lint
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1578 Release chart v3.12.2
  .github/workflows/gh-workflow-approve.yaml
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
  .github/workflows/release.yaml
  charts/metrics-server/CHANGELOG.md
  charts/metrics-server/Chart.yaml
  charts/metrics-server/README.md
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/psp.yaml
  charts/metrics-server/templates/rolebinding-nanny.yaml
  charts/metrics-server/templates/service.yaml
  charts/metrics-server/templates/servicemonitor.yaml
  charts/metrics-server/values.yaml
  manifests/base/service.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, triage/accepted

#1574 feat: Added new policy to PodDisruptionBudget
  charts/metrics-server/CHANGELOG.md
  charts/metrics-server/README.md
  charts/metrics-server/templates/pdb.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, triage/accepted
