Repository kubernetes-sigs/metrics-server, pull requests merged in 2024-02, with the labels that each got.

#1414 feat(chart): Released v3.12.0 (v0.7.0)
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
  charts/metrics-server/CHANGELOG.md
  charts/metrics-server/Chart.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#1416 feat(chart): Released v3.12.0 (v0.7.0)
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
  charts/metrics-server/CHANGELOG.md
  charts/metrics-server/Chart.yaml
  charts/metrics-server/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#1417 fix(chart): Fixed incorrect changelog version lookup
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, triage/accepted

#1423 Update kind to use v0.22.0 version to support new kubernetes version
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage
