Repository kubernetes-sigs/metrics-server, pull requests merged in 2024-08, with the labels that each got.

#1535 bump the gomod-dependencies group across 1 directory with 8 updates
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#1536 update the gomod-dependencies group in /scripts
  scripts/go.mod
  scripts/go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#1541 bump the gomod-dependencies
  cmd/metrics-server/app/options/options.go
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
  pkg/scraper/client/resource/decode.go
  pkg/server/server.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#1542 update k8s version for e2e tests
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1545 docs/command-line-flags.txt: update with latest flags
  docs/command-line-flags.txt
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, needs-triage

#1546 fix pull-metrics-server-test-version test
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1548 release-0.7 update Go dependencies
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, ok-to-test

#1551 [release-0.7] Bump Kubernetes dependencies to v0.29.8
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#1553 Cut release v0.7.2
  README.md
  manifests/components/release/kustomization.yaml
Labels: cncf-cla: yes, size/XS, approved, needs-triage
