Repository kubernetes-sigs/metrics-server, pull requests merged in 2024-05, with the labels that each got.

#1479 fix(helm): nanny rolebinding needs to be in release ns
  charts/metrics-server/CHANGELOG.md
  charts/metrics-server/templates/rolebinding-nanny.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, needs-triage

#1492 update k8s kind version to 1.30 for e2e tests
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1493 update go version to Keep in sync with Dockerfile
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1494 fix gomod-dependencies
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage
