Repository kubernetes-sigs/metrics-server, pull requests merged in 2024-09, with the labels that each got.

#1555 Add content write permissions to release jobs
  .github/workflows/gh-workflow-approve.yaml
  .github/workflows/lint-test-chart.yaml
  .github/workflows/release-chart.yaml
  .github/workflows/release.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-triage

#1560 Wire server run options to flags.
  cmd/metrics-server/app/options/options.go
  docs/command-line-flags.txt
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#1540 explicit protocol selection with appProtocol
  charts/metrics-server/templates/service.yaml
  manifests/base/service.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, triage/accepted

#1564 chore: update golang to 1.23
  Dockerfile
  Makefile
  go.mod
  scripts/go.mod
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, needs-triage

#1559 bump the gomod-dependencies group
  go.mod
  go.sum
  pkg/storage/node_test.go
  pkg/storage/pod_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, triage/accepted

#1568 feat(chart): Updated image to v0.7.2
  charts/metrics-server/CHANGELOG.md
  charts/metrics-server/Chart.yaml
  charts/metrics-server/templates/deployment.yaml
  charts/metrics-server/templates/servicemonitor.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, triage/accepted

#1569 update golangci-lint version
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage
