Repository kubernetes-sigs/metrics-server, pull requests merged in 2024-03, with the labels that each got.

#1436 Fix kubectl get PodMetrics/NodeMetrics
  pkg/api/node.go
  pkg/api/pod.go
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1435 Improve: Add hyperlink to Prometheus in README
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, triage/accepted

#1434 Improve README - Highlight content with distinctive styling
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test, triage/accepted

#1443 release-0.7: Bump golang to v1.21.8 and k8s dependencies to v1.29.2 and fix CVEs
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#1442 release-0.7: Fix kubectl get PodMetrics/NodeMetrics
  pkg/api/node.go
  pkg/api/pod.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1456 Cut release v0.7.1
  README.md
  manifests/components/release/kustomization.yaml
Labels: cncf-cla: yes, size/XS, approved, needs-triage
