Repository kubernetes-sigs/metrics-server, pull requests merged in 2025-07, with the labels that each got.

#1677 Makefile: update test-e2e to run against 1.33
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1567 chore: update versions in README and kustomization.yaml
  README.md
  manifests/components/release/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test, triage/accepted

#1648 chore: Use go tools
  Makefile
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
  scripts/go.mod
  scripts/go.sum
  scripts/tools.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#1679 Add slashpai and RainbowMango as reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-triage

#1687 chore: update k8s and prometheus dependencies
  Makefile
  go.mod
  go.sum
  pkg/scraper/client/resource/decode.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted
